sudo: required

services:
  - docker

script:
 - docker build -t hellonode/hellonode:v1 hellonode/hellonode-app/
 - ./minikube-ci-initialize.sh
 - ./kubectl create -f hellonode/hellonode-k8s-yaml/hellonode-rc.yaml
 - ./kubectl create -f hellonode/hellonode-k8s-yaml/hellonode-svc.yaml
 - SERVICE_URL="$(./minikube service --url --wait=300 --interval=2 hellonode 2>/dev/null)"
 - export SERVICE_URL
 - ./hellonode/hellonode-test.sh