sudo: required

services:
  - docker

script:
 - docker build -t hellonode/hellonode:v1 hellonode/hellonode-app/
 - ./minikube-ci-initialize.sh
 - ./kubectl create -f hellonode/hellonode-k8s-yaml/hellonode-rc.yaml
 - ./kubectl create -f hellonode/hellonode-k8s-yaml/hellonode-svc.yaml
 - ./kubectl get po
 - ./kubectl get svc
 - ./kubectl get endpoints
 - HELLONODE_URL="kubectl get svc hellonode -o go-template='{{.spec.clusterIP}}:{{ index (index .spec.ports 0) "nodePort" }}{{ "\n" }}'"
 - export HELLONODE_URL
 - ./hellonode/hellonode-test.sh