sudo: required
dist: trusty
services:
  - docker
addons:
  chrome: stable

before_install:
  - sudo apt-get install redis-tools -y

script:
 - docker build -t php-redis:v1 -f guestbook/php-redis/Dockerfile guestbook/php-redis/
 - docker build -t redis-slave:v1 -f guestbook/redis-slave/Dockerfile guestbook/redis-slave/ 
 - ./minikube-ci-initialize.sh
 - ./test.sh