apiVersion: v1                                                                     
kind: Service                                                                      
metadata:                                                                                                                
  labels:                                                                          
    app: hellonode                                                                 
  name: hellonode                                                                                                                                                                                     
spec:                                                                                                                            
  ports:                                                                                                                                         
  - port: 8080                                                                     
    protocol: TCP                                                                  
    targetPort: 8080                                                               
  selector:                                                                        
    app: hellonode                                                                                                                        
  type: NodePort                                                                      